#!/usr/bin/env python3
"""Stamp your GitHub account and author identity onto every file in this project.

Run this once, immediately after cloning or before the first push. It rewrites
the placeholders in the packaging metadata, the citation file, the docs and the
README, and inserts a provenance header at the top of every Python file.

    python scripts/set_identity.py --github-user jubymathew
    python scripts/set_identity.py --github-user jubymathew --check   # dry run

Re-running is safe: headers are replaced, not stacked.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (token, key) pairs. Tokens are deliberately non-English so that stamping this
# project can never rewrite them inside this script or inside prose.
PLACEHOLDERS = (
    ("YOUR-GITHUB-USERNAME", "github_user"),
    ("YOUR-GITHUB-REPO", "repo"),
    ("YOUR-ZENODO-ID", "zenodo"),
    ("YOUR-FULL-NAME", "author"),
    ("YOUR-EMAIL-ADDRESS", "email"),
    ("YOUR-ORCID-ID", "orcid"),
)

TEXT_SUFFIXES = {".py", ".md", ".toml", ".cff", ".yaml", ".yml", ".txt", ".cfg", ".json"}
SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "outputs", "runs", "data",
             ".pytest_cache", ".ruff_cache", "dist", "build"}

_M = "# ---"
HEADER_START = _M + " project provenance (generated by scripts/set_identity.py) " + _M[2:]
HEADER_END = _M + " end provenance " + _M[2:]


def build_header(v: dict) -> str:
    return "\n".join([
        HEADER_START,
        f"# Project : {v['repo']}",
        f"# Repo    : https://github.com/{v['github_user']}/{v['repo']}",
        f"# Author  : {v['author']} <{v['email']}>",
        f"# ORCID   : {v['orcid']}",
        "# Licence : MIT (see LICENSE)",
        "# Paper   : Engineering Research Express, manuscript ERX-121504",
        HEADER_END,
        "",
    ])


SELF = Path(__file__).resolve()


def iter_files():
    """Every text file in the project except this script, which must not stamp itself."""
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix not in TEXT_SUFFIXES:
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.resolve() == SELF:
            continue
        yield path


def replace_placeholders(text: str, values: dict) -> str:
    for token, key in PLACEHOLDERS:
        text = text.replace(token, values[key])
    return text


def apply_header(text: str, header: str) -> str:
    """Insert or refresh the provenance header, keeping any module docstring first."""
    text = re.sub(
        re.escape(HEADER_START) + r".*?" + re.escape(HEADER_END) + r"\n*",
        "", text, flags=re.S,
    )
    lines = text.split("\n")
    insert_at = 0
    if lines and lines[0].startswith("#!"):
        insert_at = 1
    # keep a module docstring above the header
    rest = "\n".join(lines[insert_at:]).lstrip()
    if rest.startswith(('"""', "'''")):
        quote = rest[:3]
        end = rest.find(quote, 3)
        if end != -1:
            consumed = rest[: end + 3]
            offset = "\n".join(lines[insert_at:]).find(consumed) + len(consumed)
            prefix = "\n".join(lines[:insert_at])
            body = "\n".join(lines[insert_at:])
            head = body[:offset]
            tail = body[offset:].lstrip("\n")
            joined = (prefix + "\n" if prefix else "") + head + "\n\n" + header + "\n" + tail
            return joined
    prefix = "\n".join(lines[:insert_at])
    body = "\n".join(lines[insert_at:]).lstrip("\n")
    return (prefix + "\n" if prefix else "") + header + "\n" + body


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--github-user", required=True, help="your GitHub username")
    ap.add_argument("--repo", default="derm-skintone-audit", help="repository name")
    ap.add_argument("--author", default="Juby Mathew")
    ap.add_argument("--email", default="jubymathew@amaljyothi.ac.in")
    ap.add_argument("--orcid", default="0000-0002-4660-5940")
    ap.add_argument("--zenodo", default="YOUR-ZENODO-ID",
                    help="Zenodo record id, once the archive exists")
    ap.add_argument("--check", action="store_true", help="dry run: report, change nothing")
    args = ap.parse_args(argv)

    values = {"github_user": args.github_user, "repo": args.repo, "author": args.author,
              "email": args.email, "orcid": args.orcid, "zenodo": args.zenodo}
    header = build_header(values)

    changed, scanned = [], 0
    for path in iter_files():
        scanned += 1
        original = path.read_text(encoding="utf-8")
        updated = replace_placeholders(original, values)
        if path.suffix == ".py":
            updated = apply_header(updated, header)
        if updated != original:
            changed.append(path.relative_to(ROOT))
            if not args.check:
                path.write_text(updated, encoding="utf-8")

    verb = "would update" if args.check else "updated"
    print(f"scanned {scanned} files; {verb} {len(changed)}")
    for p in sorted(changed):
        print(f"  {p}")

    if not args.check:
        remaining = {}
        for path in iter_files():
            body = path.read_text(encoding="utf-8")
            hits = [tok for tok, _ in PLACEHOLDERS if tok in body]
            if hits:
                remaining[path.relative_to(ROOT)] = hits
        if remaining:
            print("\nplaceholders still present (expected only for ones you did not pass):")
            for path, hits in sorted(remaining.items()):
                print(f"  {path}: {', '.join(sorted(set(hits)))}")
        else:
            print("\nno placeholders remain: every file carries your identity")
    return 0


if __name__ == "__main__":
    sys.exit(main())
